id = "nuf"
name = "Nuf"
version = "0.0.2"
schema_version = 1
authors = ["edburtnieks edburtnieks@pm.me"]
description = "Nuf support."
repository = "https://github.com/nuflang/zed-nuf"


[grammars.nuf]
repository = "https://github.com/nuflang/tree-sitter-nuf"
commit = "ff3d52498e3a388a78b2694d30de15994277c5d9"
